### ISSUE TITLE
Runtime Error with Nvidia Tesla K80

### ISSUE THREAD

**Issue by avive** [spacemeshos/gpu-post#15]
I'm compiling the lib with Cuda compute 50, 60, and 70 enabled on linux but I'm getting this error when trying to run on [TESLA K80 gpu](https://www.nvidia.com/en-gb/data-center/tesla-k80/. Was able to run on T4.

[2020-09-08 11:15:32] GPU #0: FATAL: the 't' kernel requires 5.0 capability!
[2020-09-08 11:15:32] Failed to init GPU, disabling device 0.

@AndrewAR2

**Comment by avive** [comment]
I'm able to run all other Tesla GPUs on G Cloud. Added benchmarks here: https://github.com/spacemeshos/gpu-post/blob/develop/README.md

**Comment by AndrewAR2** [comment]
TESLA K80 has Compute Capability 3.7. We support 5.0 and up.

**Comment by avive** [comment]
ok. I also see it is quite old here https://www.techpowerup.com/gpu-specs/tesla-k80.c2616.
