### ISSUE TITLE
hashLenBits' 1-7 bit range is inconsistent

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/gpu-post#16]
Calling `scryptPositions` with various values for the 1-7 bit range for `hashLenBits` param produces inconsistent outputs among different providers and sometimes to process crash. This should be fixed along with the task of extending range up to 512 bits (currently limited to 8).

**Comment by AndrewAR2** [comment]
Fixed.

**Comment by moshababo** [comment]
Thanks, works well now.

Closed by https://github.com/spacemeshos/gpu-post/commit/682a0d86f1f328fa42ed05274c559bdb21c7349b.
