### ISSUE TITLE
Build automation Requirements

### ISSUE THREAD

**Issue by avive** [spacemeshos/gpu-post#3]
We'd like to automate building releases of the library for os x, linux and windows. Building the library for a platform requires the build to run on that platform with one ore more gpu compute sdks.

For Windows builds, we need to include the CUDA and VULKAN sdks in the build host env and support a build workflow which is pure CLI with cmake and doesn't require Visual Studio.

For OS X, we need to include the VULKAN sdk in the build env host.

Ideally a cloud build can be triggered from github. For example, by creating a new release, PR or tag or by triggering a custom Github Action.

The build system should build the library binaries and its c header for all 3 platforms using a CI service such as Github Actions or Travis, and save the binary artifacts in a location that the build system of projects that use the libraries can pull them and build releases with them.

We would like the artifacts to be saved in a github branch and as assets of a github release.

For example, a desktop gpu-init app build workflow, we should be able to specify the version or tag of the library it wants to be built with and its build system should be able to pull the appropriate binary artifacts and the header file(s) for the library so it can be linked into the app. 

This is work in progress - Please share some thoughts on this.

@noamnelke @ilans @moshababo @lrettig

**Comment by moshababo** [comment]
It will be ideal if we can make it work through GitHub Actions. Need to check though if it can support the installation of the GPU SDKs.

**Comment by lrettig** [comment]
GitHub actions is surprisingly powerful and flexible. I'm pretty sure it can do everything Travis can do, and more. I suspect it can do this. Will take a look when I have a chance!

**Comment by noamnelke** [comment]
How about this as a flow:

Push a tag → this triggers a build which creates a draft release with artifacts attached (which we can then manually edit to add release notes and publish)

It should also send an email to a Google Group we’ll create in advance (gpu-post-builds@spacemesh.io) when the build completed / failed. We can make this a public group for anyone in the world that’s interested.

_Bonus points: add release notes to the draft automatically using functionality [like this](https://github.com/apps/release-drafter)._

**Comment by avive** [comment]
Part of this issue - we need the repo to package c libraries for linking with go and not only the test executable.

**Comment by avive** [comment]
Can this be closed?

**Comment by avive** [comment]
@AndrewAR2 - isn't this resolved? @moshababo can you please verify?

**Comment by AndrewAR2** [comment]
It has been fixed.

**Comment by moshababo** [comment]
Yes, it was solved.
