### ISSUE TITLE
Hash test doesn't pass

### ISSUE THREAD

**Issue by avive** [spacemeshos/gpu-post#41]
On an Apple M1 system (e.g. new mini or MBP 13):
1. Use this CI release artifacts: https://github.com/spacemeshos/gpu-post/actions/runs/863441063
2. Configure lib properly with dynamic link path and the Vulkan artifacts from the CI.
3.  Run `gpu-setup-test -u`.

Result:
[Apple M1]: hash test WRONG
[Apple M1]: 1 bits stream test OK
... rest of M1 tests are OK
[CPU]: hash test OK
....

**Comment by AndrewAR2** [comment]
Fixed.

**Comment by avive** [comment]
I can't confirm this fix due to #43

**Comment by avive** [comment]
Confirmed.
