### ISSUE TITLE
Issue running on Apple M1 cpu/gpu

### ISSUE THREAD

**Issue by avive** [spacemeshos/gpu-post#43]
1. Use lib files from: https://github.com/spacemeshos/gpu-post/actions/runs/863441063
2. Copy all files to a directory.
3. Add directory to dynamic library load path. e.g. `export LD_LIBRARY_PATH=.`
4. Make all libs and test app executable by user.
4. Run the test app and list providers. e.g. `gpu-test-app -l`.

Result: only cpu provider is listed.
Expected: M1 provider to be listed.
Env: Mac Mini M1, macOS BigSur w/o Vulkan SDK installed.

**Comment by avive** [comment]
This is still reproducible with this library release: https://github.com/spacemeshos/gpu-post/actions/runs/874060571

**Comment by AndrewAR2** [comment]
Apple M1 is an ARM64 processor and x86-64 applications run on it through a special adapter. A special MoltenVK build is required to work with the Apple M1.

**Comment by AndrewAR2** [comment]
Fixed.

**Comment by avive** [comment]
Confirmed!
