### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by avive** [spacemeshos/gpu-post#45]
Running unit tests (test app with -u flag) causes macOS to run out of system apps memory.
This happens on systems with 8GB or 16GB of Ram.
To repro try `./gpu-setup-test -u`.

**Comment by avive** [comment]
@AndrewAR2 - not sure if this is a reproducible issue. Can you please have a look?

**Comment by AndrewAR2** [comment]
I have not been able to reproduce this. Also I checked the code of this and found no reason for the memory overflow.
