### ISSUE TITLE
[Metrics] v0.1.20 Test Results

### ISSUE THREAD

**Issue by Jaga-Telesin** [spacemeshos/gpu-post#49]
Posting this here as a feedback thread.  Information includes system details and benchmark results for v0.1.20. 
Discord nick:  Obsidian (Jᴧgᴧ)

=================================
System:
OS: Windows 10 Pro v20H2, Build 19042.985
CPU: Intel i7-6700K @ 4.6ghz (HT enabled: 4c/8t)
GPU:  Nvidia RTX 2080ti 11GB @ stock (1350mhz / 7000mhz)
Video Driver:  Nvidia 466.11
CUDA Driver: Nvidia CUDA 11.3.70

=================================
Geekbench 5:
Compute API:  CUDA
Compute Benchmark:  169601

=================================
GPU-Post v0.1.20:
Test param:  .\gpu-setup-test -t
3-run median result:  NVIDIA GeForce RTX 2080 Ti: 131072 hashes, 1198602 h/s

Test param:  .\gpu-setup-test -b -n 2000000
5-run median result:  2560603

**Comment by avive** [comment]
Thank you for posting - ~2.5 mhps - not bad! For future reports please use `.\gpu-setup-test -b -n 2000000` and not `-t`.

**Comment by avive** [comment]
Added to benchmark
