### ISSUE TITLE
Investigate sdk support for ARM systems

### ISSUE THREAD

**Issue by avive** [spacemeshos/gpu-post#56]
Look into creating libs for Window 10, macOS Linux ARM cpus in addition to amd-64. We should add these build targets to the lib if cuda and vulkan libs support this.

**Comment by lrettig** [comment]
I think we need this for Mac M1/arm64 as well don't we? See https://github.com/spacemeshos/go-spacemesh/issues/2642

**Comment by avive** [comment]
yes, for all 3 platforms - i've clarified the issue.

**Comment by lrettig** [comment]
Assuming this library actually does build on ARM, it should be possible to set up a self-hosted github actions runner to do this. See https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/ and https://github.com/actions/runner/issues/805.

**Comment by avive** [comment]
We have started a dev cycle to implement the lib for linux-arm and for macOS-arm. @lrettig
