### ISSUE TITLE
Support Linux-arm architecture

### ISSUE THREAD

**Issue by avive** [spacemeshos/gpu-post#58]
# Motivation
Allow users running modern Linux-arm (w appropriate cuda or vulkan hardware and drivers) to use the library and to create post data.

# Overview 
- Build the lib for linux-arm64 arch.
- Update CI to run all builds and tests on linux-arm64.
- Update docs regarding supported linux arm systems.

**Comment by AndrewAR2** [comment]
PR https://github.com/spacemeshos/gpu-post/pull/61
