### ISSUE TITLE
Support macOS-arm architecture

### ISSUE THREAD

**Issue by avive** [spacemeshos/gpu-post#59]
# Motivation
Provide the library as a native macOS-arm lib. e.g. Macs with Mx CPU/GPU.

# Overview
- Add macOS-arm compilation target.
- Update CI tests to run on macOS-arm arch (and not in macOS-amd emulation).
- Update release artifacts to include macOS-arm.

**Comment by AndrewAR2** [comment]
PR https://github.com/spacemeshos/gpu-post/pull/60
